config/routes.rb
BurningAirlines::Application.routes.draw do
  resources :airplanes

  resources :flights

  resources :reservations


  get '/search' => 'search#index', :as => :search

  resources :seats


  devise_for :users

  root to: "pages#index"
end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
  has_many :flights, dependent: :destroy

  validates :name, presence: true
  validates :rows, presence: true
  validates :columns, presence: true
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplane = Airplane.new
    @airplanes = Airplane.all
    @users = User.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
    respond_to do |format|
      format.json { render json: @airplane }
    end
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)
    authorize @airplane

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render json: @airplane }
      else
        format.html { render action: 'new' }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    authorize @airplane
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    authorize @airplane
    respond_to do |format|
      format.html { redirect_to airplanes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :rows, :columns)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(@airplane) do |f| %>
  <% if @airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% @airplane.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, id:'new-name', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rows %><br>
    <%= f.number_field :rows, id:'new-rows', :class => 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :columns %><br>
    <%= f.text_field :columns, id:'new-columns', :class => 'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit id:'create-new', :class => 'btn btn-warning' %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing airplane</h1>



<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<div class="container">
  
  <div class="row">

    <div id="table" class='col-md-4'>
    <h1><strong>In our fleet</strong></h1>
    <p>Please select our planes to see a detailed version of our airplanes and their capacity</p>
    <hr></hr>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Rows</th>
          <th>Columns</th>
          <% if policy(@airplanes).create? %>
          <th></th>
          <% end %>
        </tr>
      </thead>
  
      <tbody id="table-body">
        <% @airplanes.each do |airplane| %>
          <tr>
            <td><strong><%= link_to airplane.name,"#", id:"#{airplane.id}", :class => "plane" %></strong></td>
            <td><%= airplane.rows %></td>
            <td><%= airplane.columns %></td>
            <% if policy(@airplanes).create? %>
            <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>

  <div class="col-md-5">
    <div id="diagram">

    </div>
  </div>

  <div class='col-md-3'>
    <% if policy(@airplanes).create? %>
    <%= link_to 'Create Airplane', "#new", id:'new-plane', class: 'btn btn-default' %>
    <% end %>
    <div id="form">
      <%= render 'form' %>
    </div>

  </div>
  </div>

</div>

<div id="token"><%= form_authenticity_token %></div>

<script>

  $(document).ready(function() {
  
  var planeArray = []

  $('#form').hide();

  $('#new-plane').on('click', function(){
    $('#form').toggle();
  })

  $('#create-new').on('click',function(e){
    e.preventDefault();

    var planeName = $('#new-name').val()
    var planeRows = $('#new-rows').val()
    var planeColumns = $('#new-columns').val()
    
    var saveOption = {
      url: '/airplanes',
      type: 'post',
      dataType: 'json',
      data: { 
        airplane: {
          name: planeName, 
          rows: planeRows, 
          columns: planeColumns, 
          token: $('#token').html() 
        }
      }
    }

    var savePlane = $.ajax(saveOption);

    savePlane.done(function(plane){
      appendPlane(plane)
      appendToTable(plane)
      resetForm();
      }).fail(function(){
      alert('cant save it!');
      })

  }) // create on click

    var appendToTable = function(plane){
      var $newTableRow = $("<tr></tr>")

      $newTableRow = $newTableRow.append("<td><strong><a href='#' id='" + plane.id + "' class='plane'>" + plane.name + "</a></strong></td>")
      $newTableRow = $newTableRow.append("<td>" + plane.rows + "</td>")
      $newTableRow = $newTableRow.append("<td>" + plane.columns + "</td>")
      $newTableRow = $newTableRow.append("<td><a href='/airplanes/" + plane.id + "/edit'>Edit</a></td>").addClass('btn btn-default');
      $newTableRow = $newTableRow.append("<td><a data-confirm='Are you sure?' data-method='delete' href='/airplanes/" + plane.id + "' rel='nofollow'>Destroy</a></td>").addClass('btn btn-warning');

      $('#table-body').append($newTableRow)

    }

    var appendPlane = function(plane){
      $('#diagram').empty()
      var diagram = planeDiagram(plane);
      $('#diagram').append('<h3>' + plane.name + '</h3>')
      $('#diagram').append(diagram);
    }

    var planeDiagram = function(plane){
      var $plane = plane
      var seatDiv = '<div class="glyphicon glyphicon-plane"></div>'
      var planeDiv = '<div class="airplane"></div>'

      for( var x = 1; x <= $plane.rows ; x = x+1 ){
          var row  = '<div class"row"></div>'
          for ( var i = 1; i <= $plane.columns; i = i+1 ) {
            row = $(row).append(seatDiv)
          }
          planeDiv = $(planeDiv).append(row)          
        }
      return planeDiv
      } // planeDiagram

    var resetForm = function(){
      $('#new-name').val("")
      $('#new-rows').val("")
      $('#new-columns').val("")
      $('#form').toggle();
    }


  $('#table').on('click','.plane', function(e){
    e.preventDefault();
    planeId = parseInt(this.id);
    if (planeArray.length === 0 ) {
      findGettingPlanesList(planeId);
    } else  { 
      var presentIntoArray = ""

      for ( var i = 0 ; i < planeArray.length; i++ ){
        if (planeArray[i].id === planeId) { 
          presentIntoArray = planeArray[i]
        }} // for loop
        
        if ( presentIntoArray != "" ) {
          appendPlane(presentIntoArray)
        } else {
          debugger;
        }
    }
    }) // end function on click .plane


  $('#diagram').on('click', '.glyphicon', function(){
    console.log('click')
  })

  var findGettingPlanesList = function(id){
    planeId = parseInt(id);
    var deferred = $.ajax({
      url: '/airplanes',
      dataType: 'json',
      // data: { id: 1 },
    })

    deferred.done(function(planesList){
      $.each(planesList, function(index, plane) {
        planeArray.push(plane)
      if (plane.id === planeId ) {
          appendPlane(plane)
        }
      })
     });
  }
}) // document ready


</script>

app/views/airplanes/new.html.erb
<h1>New airplane</h1>

<%= render 'form' %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @airplane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @airplane.columns %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>