config/routes.rb
BurningAirlines::Application.routes.draw do
  resources :airplanes

  resources :flights

  resources :reservations


  get '/search' => 'search#index', :as => :search

  resources :seats


  devise_for :users

  root to: "pages#index"
end

app/views/shared/_footer.html.erb
<div class="footer navbar-fixed-bottom">
<p>Emily, Luke, Federico</p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BURNING AIRLINES</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Airplanes', airplanes_path %></li>
        <li><%= link_to 'All Flights', flights_path %></li>
        <li><%= link_to 'Search', search_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.email if current_user %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle element" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li><%= link_to 'User Settigns', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </li>    
      </ul>
    </div>

    
  </div>
</nav>

app/views/shared/old_merge_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BURNING AIRLINES</a>
    </div>

<<<<<<< HEAD
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Flights', flights_path %></li>
        <li><%= link_to 'Airplanes', airplanes_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.email if current_user %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle element" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li><%= link_to 'User Settigns', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </li>    
      </ul>
    </div>

    
  </div>
</nav>
=======
    <ul class="nav navbar-nav navbar-right">

    <li><a href="#"><%= current_user.email if current_user %></a></li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle element" data-toggle="dropdown">Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
          <li><%= link_to 'User Settigns', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </li>    
    </ul>
  </div>
</nav>
<section>
  <%= link_to 'Flights', flights_path, :class => "btn btn-default" %>
  <%= link_to 'Airplanes', airplanes_path, :class => "btn btn-default" %>
  <%= link_to 'Reservations', reservations_path, :class => "btn btn-default" %>
  <%= link_to 'Search', search_path, :class => "btn btn-default" %>
<section>
>>>>>>> master